version: "3.8"
services:
  frontend:
    build:
      context: .
      args:
        WORKDIR: $WORKDIR
    # Node.jsのグローバル変数です。開発用途なのでdevelopmentを指定します。
    environment:
      - NODE_ENV=development
    volumes:
      - "./:/${WORKDIR}"
    command: sh -c 'cd frontend && yarn start'
    ports:
      - 8000:3000
    tty: true
